CREATE TABLE [dbo].[Dim_Date] (
    [Date Key]                 INT          NOT NULL,
    [Date]                     DATE         NOT NULL,
    [Day]                      TINYINT      NOT NULL,
    [Day Suffix]               CHAR (2)     NOT NULL,
    [Weekday]                  TINYINT      NOT NULL,
    [Weekday Name]             VARCHAR (10) NOT NULL,
    [Weekday Name Short]       CHAR (3)     NOT NULL,
    [Weekday Name FirstLetter] CHAR (1)     NOT NULL,
    [Day Of Year]              SMALLINT     NOT NULL,
    [Week Of Month]            TINYINT      NOT NULL,
    [Week Of Year]             TINYINT      NOT NULL,
    [Month]                    TINYINT      NOT NULL,
    [Month Name]               VARCHAR (10) NOT NULL,
    [Month Name Short]         CHAR (3)     NOT NULL,
    [Month Name FirstLetter]   CHAR (1)     NOT NULL,
    [Quarter]                  TINYINT      NOT NULL,
    [Quarter Name]             VARCHAR (6)  NOT NULL,
    [Year]                     INT          NOT NULL,
    [MMYYYY]                   CHAR (6)     NOT NULL,
    [Month Year]               CHAR (7)     NOT NULL,
    [Is Weekend]               BIT          DEFAULT ((0)) NOT NULL,
    [Is Holiday]               BIT          DEFAULT ((0)) NOT NULL,
    [Holiday Name]             VARCHAR (20) DEFAULT ('') NOT NULL,
    [Special Day]              VARCHAR (20) DEFAULT ('') NOT NULL,
    [First Date Of Year]       DATE         NULL,
    [Last Date Of Year]        DATE         NULL,
    [First Date Of Quater]     DATE         NULL,
    [Last Date Of Quater]      DATE         NULL,
    [First Date Of Month]      DATE         NULL,
    [Last Date Of Month]       DATE         NULL,
    [First Date Of Week]       DATE         NULL,
    [Last Date Of Week]        DATE         NULL,
    [Lineage Key]              INT          NULL,
    PRIMARY KEY CLUSTERED ([Date Key] ASC)
);